spring:
  application:
    name: wallet-settlement-system

  datasource:
    url: jdbc:postgresql://postgres:5432/walletdb
    username: wallet_user
    password: wallet_pass
    driver-class-name: org.postgresql.Driver

  flyway:
    clean-disabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8080
  error:
    include-message: always
